permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl mingw-w64

      - name: Install rust
        run: |
          curl https://sh.rustup.rs > rustup.sh
          chmod +x rustup.sh
          ./rustup.sh --profile=default --default-toolchain=nightly -y
          export PATH="$HOME/.cargo/bin:$PATH"
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup target add x86_64-unknown-linux-gnu
          rustup target add x86_64-pc-windows-gnu
          rustup component add rust-src

      - name: Setup mold
        uses: rui314/setup-mold@v1

      - name: Compile for linux
        run: |
          cargo build -Z build-std --release --target x86_64-unknown-linux-gnu
          mv -v \
            target/x86_64-unknown-linux-gnu/release/bread-launcher \
            linux-x86_64-bread-launcher.elf

      - name: Compile for windows
        run: |
          cargo build -Z build-std --release --target x86_64-pc-windows-gnu
          mv -v \
            target/x86_64-pc-windows-gnu/release/bread-launcher.exe \
            windows-x86_64-bread-launcher.exe

      - name: Edit release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          make_latest: true
          files: |
            linux-x86_64-bread-launcher.elf
            windows-x86_64-bread-launcher.exe
